// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/deploy-config": {
            "get": {
                "description": "分页获取部署配置列表，支持按项目ID和分支名称过滤",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "部署配置管理"
                ],
                "summary": "获取部署配置列表",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "页码",
                        "name": "pageNum",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "每页数量",
                        "name": "pageSize",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "项目ID精确查询",
                        "name": "project_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "分支名称模糊查询",
                        "name": "branch",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "获取成功",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    },
                    "500": {
                        "description": "获取失败",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    }
                }
            },
            "post": {
                "description": "为指定项目创建新的部署配置，每个项目的每个分支只能有一个配置",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "部署配置管理"
                ],
                "summary": "创建部署配置",
                "parameters": [
                    {
                        "description": "部署配置信息",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.DeployConfigCreateRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "创建成功",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    },
                    "500": {
                        "description": "创建失败",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    }
                }
            }
        },
        "/api/deploy-config/project/{project_id}": {
            "get": {
                "description": "获取指定项目的所有部署配置",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "部署配置管理"
                ],
                "summary": "根据项目ID获取部署配置列表",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "项目ID",
                        "name": "project_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "获取成功",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    },
                    "400": {
                        "description": "ID格式错误",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    },
                    "500": {
                        "description": "获取失败",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    }
                }
            }
        },
        "/api/deploy-config/project/{project_id}/branch/{branch}": {
            "get": {
                "description": "根据项目ID和分支名称获取特定的部署配置",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "部署配置管理"
                ],
                "summary": "根据项目和分支获取部署配置",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "项目ID",
                        "name": "project_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "分支名称",
                        "name": "branch",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "获取成功",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    },
                    "400": {
                        "description": "参数格式错误",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    },
                    "404": {
                        "description": "部署配置不存在",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    },
                    "500": {
                        "description": "获取失败",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    }
                }
            }
        },
        "/api/deploy-config/{id}": {
            "get": {
                "description": "根据ID获取指定部署配置的详细信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "部署配置管理"
                ],
                "summary": "获取部署配置详情",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "部署配置ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "获取成功",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    },
                    "400": {
                        "description": "ID格式错误",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    },
                    "404": {
                        "description": "部署配置不存在",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    },
                    "500": {
                        "description": "获取失败",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    }
                }
            },
            "put": {
                "description": "根据ID更新指定部署配置的信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "部署配置管理"
                ],
                "summary": "更新部署配置",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "部署配置ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "更新信息",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.DeployConfigUpdateRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "更新成功",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    },
                    "400": {
                        "description": "ID格式错误",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    },
                    "404": {
                        "description": "部署配置不存在",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    },
                    "500": {
                        "description": "更新失败",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    }
                }
            },
            "delete": {
                "description": "根据ID删除指定部署配置（软删除）",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "部署配置管理"
                ],
                "summary": "删除部署配置",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "部署配置ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "删除成功",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    },
                    "400": {
                        "description": "ID格式错误",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    },
                    "404": {
                        "description": "部署配置不存在",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    },
                    "500": {
                        "description": "删除失败",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    }
                }
            }
        },
        "/api/deploy-record": {
            "get": {
                "description": "分页获取部署记录列表，支持按项目ID、项目名称、分支、状态、时间范围过滤",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "部署记录管理"
                ],
                "summary": "获取部署记录列表",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "页码",
                        "name": "pageNum",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "每页数量",
                        "name": "pageSize",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "项目ID精确查询",
                        "name": "project_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "项目名称模糊查询",
                        "name": "project_name",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "分支模糊查询",
                        "name": "branch",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "状态精确查询",
                        "name": "status",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "开始时间范围查询-开始",
                        "name": "start_time_start",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "开始时间范围查询-结束",
                        "name": "start_time_end",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "获取成功",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    },
                    "500": {
                        "description": "获取失败",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    }
                }
            },
            "post": {
                "description": "创建新的部署记录",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "部署记录管理"
                ],
                "summary": "创建部署记录",
                "parameters": [
                    {
                        "description": "部署记录信息",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.DeployRecordCreateRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "创建成功",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    },
                    "500": {
                        "description": "创建失败",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    }
                }
            }
        },
        "/api/deploy-record/branch/{branch}": {
            "get": {
                "description": "获取指定分支的所有部署记录",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "部署记录管理"
                ],
                "summary": "根据分支获取部署记录列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "分支名称",
                        "name": "branch",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "获取成功",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    },
                    "500": {
                        "description": "获取失败",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    }
                }
            }
        },
        "/api/deploy-record/project/{project_id}": {
            "get": {
                "description": "获取指定项目的所有部署记录",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "部署记录管理"
                ],
                "summary": "根据项目ID获取部署记录列表",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "项目ID",
                        "name": "project_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "获取成功",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    },
                    "400": {
                        "description": "ID格式错误",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    },
                    "500": {
                        "description": "获取失败",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    }
                }
            }
        },
        "/api/deploy-record/project/{project_id}/branch/{branch}/latest": {
            "get": {
                "description": "获取指定项目和分支的最新部署记录",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "部署记录管理"
                ],
                "summary": "获取项目和分支的最新部署记录",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "项目ID",
                        "name": "project_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "分支名称",
                        "name": "branch",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "获取成功",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    },
                    "400": {
                        "description": "参数格式错误",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    },
                    "404": {
                        "description": "部署记录不存在",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    },
                    "500": {
                        "description": "获取失败",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    }
                }
            }
        },
        "/api/deploy-record/stats": {
            "get": {
                "description": "获取部署记录的统计信息，包括总次数、成功次数、失败次数、运行中次数",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "部署记录管理"
                ],
                "summary": "获取部署记录统计信息",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "项目ID（可选，不传则统计所有项目）",
                        "name": "project_id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "获取成功",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    },
                    "500": {
                        "description": "获取失败",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    }
                }
            }
        },
        "/api/deploy-record/status/{status}": {
            "get": {
                "description": "获取指定状态的所有部署记录",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "部署记录管理"
                ],
                "summary": "根据状态获取部署记录列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "状态",
                        "name": "status",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "获取成功",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    },
                    "500": {
                        "description": "获取失败",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    }
                }
            }
        },
        "/api/deploy-record/{id}": {
            "get": {
                "description": "根据ID获取指定部署记录的详细信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "部署记录管理"
                ],
                "summary": "获取部署记录详情",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "部署记录ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "获取成功",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    },
                    "400": {
                        "description": "ID格式错误",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    },
                    "404": {
                        "description": "部署记录不存在",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    },
                    "500": {
                        "description": "获取失败",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    }
                }
            },
            "put": {
                "description": "根据ID更新指定部署记录的信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "部署记录管理"
                ],
                "summary": "更新部署记录",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "部署记录ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "更新信息",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.DeployRecordUpdateRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "更新成功",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    },
                    "400": {
                        "description": "ID格式错误",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    },
                    "404": {
                        "description": "部署记录不存在",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    },
                    "500": {
                        "description": "更新失败",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    }
                }
            },
            "delete": {
                "description": "根据ID删除指定部署记录（软删除）",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "部署记录管理"
                ],
                "summary": "删除部署记录",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "部署记录ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "删除成功",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    },
                    "400": {
                        "description": "ID格式错误",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    },
                    "404": {
                        "description": "部署记录不存在",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    },
                    "500": {
                        "description": "删除失败",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    }
                }
            }
        },
        "/api/host": {
            "get": {
                "description": "分页获取主机配置列表，支持pageNum和pageSize参数，支持主机名模糊查询、IP精确查询、状态精确查询",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "hosts"
                ],
                "summary": "分页获取主机列表",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "页码",
                        "name": "pageNum",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "每页条数",
                        "name": "pageSize",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "主机名模糊查询",
                        "name": "name",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "IP地址精确查询",
                        "name": "host",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "主机状态精确查询",
                        "name": "status",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "获取成功",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    }
                }
            },
            "post": {
                "description": "创建新的SSH主机配置",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "hosts"
                ],
                "summary": "创建主机",
                "parameters": [
                    {
                        "description": "主机信息",
                        "name": "host",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.Host"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "创建成功",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    }
                }
            }
        },
        "/api/host/batch-check": {
            "post": {
                "description": "批量检查所有主机的SSH连接状态并更新",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "SSH操作"
                ],
                "summary": "批量检查主机状态",
                "responses": {
                    "200": {
                        "description": "检查完成",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    },
                    "500": {
                        "description": "检查失败",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    }
                }
            }
        },
        "/api/host/docker/build": {
            "post": {
                "description": "在指定主机上构建Docker镜像",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Docker管理"
                ],
                "summary": "构建Docker镜像",
                "parameters": [
                    {
                        "description": "Docker构建请求",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.DockerBuildRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "构建成功",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    },
                    "500": {
                        "description": "构建失败",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    }
                }
            }
        },
        "/api/host/docker/execute": {
            "post": {
                "description": "通过SSH连接在指定主机上执行Docker命令",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Docker管理"
                ],
                "summary": "通过SSH执行Docker命令",
                "parameters": [
                    {
                        "description": "Docker命令执行请求",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.SSHCommandRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "执行成功",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    },
                    "500": {
                        "description": "执行失败",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    }
                }
            }
        },
        "/api/host/docker/info": {
            "post": {
                "description": "获取指定主机的Docker信息和状态",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Docker管理"
                ],
                "summary": "获取Docker信息",
                "parameters": [
                    {
                        "description": "Docker信息请求",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.DockerInfoRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "获取成功",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    },
                    "500": {
                        "description": "获取失败",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    }
                }
            }
        },
        "/api/host/docker/run": {
            "post": {
                "description": "在指定主机上运行Docker容器",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Docker管理"
                ],
                "summary": "运行Docker容器",
                "parameters": [
                    {
                        "description": "Docker运行请求",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.DockerRunRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "运行成功",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    },
                    "500": {
                        "description": "运行失败",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    }
                }
            }
        },
        "/api/host/execute": {
            "post": {
                "description": "在指定主机上执行SSH命令",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "SSH操作"
                ],
                "summary": "执行SSH命令",
                "parameters": [
                    {
                        "description": "命令执行请求",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.SSHCommandRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "执行成功",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    },
                    "500": {
                        "description": "执行失败",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    }
                }
            }
        },
        "/api/host/upload/directory": {
            "post": {
                "description": "通过SSH上传整个目录到指定主机",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "文件管理"
                ],
                "summary": "上传目录",
                "parameters": [
                    {
                        "description": "目录上传请求",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.DirectoryUploadRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "上传成功",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    },
                    "500": {
                        "description": "上传失败",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    }
                }
            }
        },
        "/api/host/upload/file": {
            "post": {
                "description": "通过SSH上传单个文件到指定主机",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "文件管理"
                ],
                "summary": "上传单个文件",
                "parameters": [
                    {
                        "description": "文件上传请求",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.FileUploadRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "上传成功",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    },
                    "500": {
                        "description": "上传失败",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    }
                }
            }
        },
        "/api/host/{id}": {
            "get": {
                "description": "根据ID获取指定主机的详细信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "hosts"
                ],
                "summary": "获取主机详情",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "主机ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "获取成功",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    },
                    "400": {
                        "description": "ID格式错误",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    },
                    "404": {
                        "description": "主机不存在",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    }
                }
            },
            "put": {
                "description": "更新指定主机的配置信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "hosts"
                ],
                "summary": "更新主机信息",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "主机ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "更新的主机信息",
                        "name": "host",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "更新成功",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    },
                    "400": {
                        "description": "ID格式错误或请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    },
                    "404": {
                        "description": "主机不存在",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    }
                }
            },
            "delete": {
                "description": "根据ID删除指定主机（软删除）",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "hosts"
                ],
                "summary": "删除主机",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "主机ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "删除成功",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    },
                    "400": {
                        "description": "ID格式错误",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    },
                    "404": {
                        "description": "主机不存在",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    }
                }
            }
        },
        "/api/host/{id}/test": {
            "post": {
                "description": "测试指定主机的SSH连接是否正常",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "SSH操作"
                ],
                "summary": "测试SSH连接",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "主机ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "连接成功",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    },
                    "400": {
                        "description": "ID格式错误",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    },
                    "500": {
                        "description": "连接失败",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    }
                }
            }
        },
        "/api/project": {
            "get": {
                "description": "获取所有项目列表，支持分页和条件查询",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "项目管理"
                ],
                "summary": "获取项目列表",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "页码",
                        "name": "pageNum",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "每页数量",
                        "name": "pageSize",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "项目名称模糊查询",
                        "name": "name",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "项目编码模糊查询",
                        "name": "code",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "获取成功",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    },
                    "500": {
                        "description": "获取失败",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    }
                }
            },
            "post": {
                "description": "创建新的项目",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "项目管理"
                ],
                "summary": "创建项目",
                "parameters": [
                    {
                        "description": "项目信息",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.ProjectCreateRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "创建成功",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    },
                    "500": {
                        "description": "创建失败",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    }
                }
            }
        },
        "/api/project/check-code": {
            "get": {
                "description": "检查项目编码是否已存在，用于新增和更新时的唯一性验证",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "项目管理"
                ],
                "summary": "检查项目编码是否存在",
                "parameters": [
                    {
                        "type": "string",
                        "description": "项目编码",
                        "name": "code",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "排除的项目ID（用于更新时检查）",
                        "name": "excludeId",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "检查完成",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    }
                }
            }
        },
        "/api/project/code/{code}": {
            "get": {
                "description": "根据项目编码获取项目信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "项目管理"
                ],
                "summary": "根据项目编码获取项目",
                "parameters": [
                    {
                        "type": "string",
                        "description": "项目编码",
                        "name": "code",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "获取成功",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    },
                    "404": {
                        "description": "项目不存在",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    }
                }
            }
        },
        "/api/project/{id}": {
            "get": {
                "description": "根据ID获取指定项目的详细信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "项目管理"
                ],
                "summary": "获取项目详情",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "项目ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "获取成功",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    },
                    "400": {
                        "description": "ID格式错误",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    },
                    "404": {
                        "description": "项目不存在",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    }
                }
            },
            "put": {
                "description": "根据ID更新指定项目的信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "项目管理"
                ],
                "summary": "更新项目",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "项目ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "更新信息",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.ProjectUpdateRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "更新成功",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    },
                    "400": {
                        "description": "ID格式错误",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    },
                    "404": {
                        "description": "项目不存在",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    },
                    "500": {
                        "description": "更新失败",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    }
                }
            },
            "delete": {
                "description": "根据ID删除指定项目（软删除）",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "项目管理"
                ],
                "summary": "删除项目",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "项目ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "删除成功",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    },
                    "400": {
                        "description": "ID格式错误",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    },
                    "404": {
                        "description": "项目不存在",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    },
                    "500": {
                        "description": "删除失败",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "description": "检查服务运行状态",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "心跳接口"
                ],
                "summary": "健康检查",
                "responses": {
                    "200": {
                        "description": "服务正常",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.CustomTime": {
            "type": "object",
            "properties": {
                "time.Time": {
                    "type": "string"
                }
            }
        },
        "models.DeployConfigCreateRequest": {
            "type": "object"
        },
        "models.DeployConfigItem": {
            "type": "object"
        },
        "models.DeployConfigUpdateRequest": {
            "type": "object"
        },
        "models.DeployRecordCreateRequest": {
            "type": "object",
            "required": [
                "branch",
                "project_id",
                "project_name",
                "start_time"
            ],
            "properties": {
                "branch": {
                    "description": "分支",
                    "type": "string",
                    "example": "main"
                },
                "duration": {
                    "description": "耗时（秒）",
                    "type": "integer",
                    "example": 300
                },
                "log_path": {
                    "description": "日志文件路径",
                    "type": "string",
                    "example": "/var/log/deploy/20240101_120000.log"
                },
                "project_id": {
                    "description": "项目ID",
                    "type": "integer",
                    "example": 1
                },
                "project_name": {
                    "description": "项目名称",
                    "type": "string",
                    "example": "我的项目"
                },
                "start_time": {
                    "description": "开始执行时间",
                    "type": "string",
                    "example": "2024-01-01 12:00:00"
                },
                "status": {
                    "description": "部署状态：running, success, failed",
                    "type": "string",
                    "example": "running"
                }
            }
        },
        "models.DeployRecordUpdateRequest": {
            "type": "object",
            "properties": {
                "branch": {
                    "description": "分支",
                    "type": "string",
                    "example": "main"
                },
                "duration": {
                    "description": "耗时（秒）",
                    "type": "integer",
                    "example": 300
                },
                "log_path": {
                    "description": "日志文件路径",
                    "type": "string",
                    "example": "/var/log/deploy/20240101_120000.log"
                },
                "project_id": {
                    "description": "项目ID",
                    "type": "integer",
                    "example": 1
                },
                "project_name": {
                    "description": "项目名称",
                    "type": "string",
                    "example": "我的项目"
                },
                "start_time": {
                    "description": "开始执行时间",
                    "type": "string",
                    "example": "2024-01-01 12:00:00"
                },
                "status": {
                    "description": "部署状态：running, success, failed",
                    "type": "string",
                    "example": "success"
                }
            }
        },
        "models.DirectoryFileItem": {
            "type": "object",
            "required": [
                "content",
                "path"
            ],
            "properties": {
                "content": {
                    "description": "文件内容",
                    "type": "string",
                    "example": "Hello World"
                },
                "is_dir": {
                    "description": "是否为目录",
                    "type": "boolean",
                    "example": false
                },
                "path": {
                    "description": "相对路径",
                    "type": "string",
                    "example": "subdir/file.txt"
                },
                "permissions": {
                    "description": "文件权限（可选）",
                    "type": "string",
                    "example": "0644"
                }
            }
        },
        "models.DirectoryUploadRequest": {
            "type": "object",
            "required": [
                "files",
                "host_id",
                "remote_path"
            ],
            "properties": {
                "files": {
                    "description": "文件列表",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.DirectoryFileItem"
                    }
                },
                "host_id": {
                    "description": "主机ID",
                    "type": "integer",
                    "example": 1
                },
                "overwrite": {
                    "description": "是否覆盖已存在的文件",
                    "type": "boolean",
                    "example": true
                },
                "remote_path": {
                    "description": "远程目录路径",
                    "type": "string",
                    "example": "/root/test_dir"
                }
            }
        },
        "models.DockerBuildRequest": {
            "type": "object",
            "required": [
                "host_id",
                "image_name"
            ],
            "properties": {
                "build_args": {
                    "description": "构建参数",
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "context_path": {
                    "description": "构建上下文路径",
                    "type": "string",
                    "example": "."
                },
                "dockerfile": {
                    "description": "Dockerfile路径",
                    "type": "string",
                    "example": "Dockerfile"
                },
                "host_id": {
                    "description": "主机ID",
                    "type": "integer",
                    "example": 1
                },
                "image_name": {
                    "description": "镜像名称",
                    "type": "string",
                    "example": "devops-app"
                },
                "image_tag": {
                    "description": "镜像标签",
                    "type": "string",
                    "example": "latest"
                },
                "timeout": {
                    "description": "超时时间（秒）",
                    "type": "integer",
                    "example": 300
                }
            }
        },
        "models.DockerInfoRequest": {
            "type": "object",
            "required": [
                "host_id"
            ],
            "properties": {
                "host_id": {
                    "description": "主机ID",
                    "type": "integer",
                    "example": 1
                }
            }
        },
        "models.DockerRunRequest": {
            "type": "object",
            "required": [
                "host_id",
                "image_name"
            ],
            "properties": {
                "command": {
                    "description": "运行命令",
                    "type": "string",
                    "example": "./app"
                },
                "container_name": {
                    "description": "容器名称",
                    "type": "string",
                    "example": "test-container"
                },
                "detach": {
                    "description": "是否后台运行",
                    "type": "boolean",
                    "example": true
                },
                "env_vars": {
                    "description": "环境变量",
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "host_id": {
                    "description": "主机ID",
                    "type": "integer",
                    "example": 1
                },
                "image_name": {
                    "description": "镜像名称",
                    "type": "string",
                    "example": "devops-app"
                },
                "image_tag": {
                    "description": "镜像标签",
                    "type": "string",
                    "example": "latest"
                },
                "port_bindings": {
                    "description": "端口绑定",
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "timeout": {
                    "description": "超时时间（秒）",
                    "type": "integer",
                    "example": 60
                },
                "volumes": {
                    "description": "卷映射",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.DockerVolumeMapping"
                    }
                }
            }
        },
        "models.DockerVolumeMapping": {
            "type": "object",
            "properties": {
                "container_path": {
                    "description": "容器路径",
                    "type": "string",
                    "example": "/container/path"
                },
                "host_path": {
                    "description": "主机路径",
                    "type": "string",
                    "example": "/host/path"
                },
                "mode": {
                    "description": "读写模式：rw/ro",
                    "type": "string",
                    "example": "rw"
                }
            }
        },
        "models.FileUploadRequest": {
            "type": "object",
            "required": [
                "content",
                "host_id",
                "remote_path"
            ],
            "properties": {
                "content": {
                    "description": "文件内容",
                    "type": "string",
                    "example": "Hello World"
                },
                "host_id": {
                    "description": "主机ID",
                    "type": "integer",
                    "example": 1
                },
                "overwrite": {
                    "description": "是否覆盖已存在的文件",
                    "type": "boolean",
                    "example": true
                },
                "permissions": {
                    "description": "文件权限（可选）",
                    "type": "string",
                    "example": "0644"
                },
                "remote_path": {
                    "description": "远程路径",
                    "type": "string",
                    "example": "/root/test.txt"
                }
            }
        },
        "models.Host": {
            "type": "object",
            "properties": {
                "auth_type": {
                    "description": "password, key",
                    "type": "string"
                },
                "created_at": {
                    "$ref": "#/definitions/models.CustomTime"
                },
                "host": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "port": {
                    "type": "integer"
                },
                "remark": {
                    "description": "备注信息",
                    "type": "string"
                },
                "status": {
                    "description": "online, offline",
                    "type": "string"
                },
                "updated_at": {
                    "$ref": "#/definitions/models.CustomTime"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "models.ProjectCreateRequest": {
            "type": "object",
            "required": [
                "code",
                "name"
            ],
            "properties": {
                "code": {
                    "description": "项目编码",
                    "type": "string",
                    "example": "PROJECT001"
                },
                "git_password": {
                    "description": "Git密码",
                    "type": "string",
                    "example": "gitpassword"
                },
                "git_repo": {
                    "description": "Git仓库地址",
                    "type": "string",
                    "example": "https://github.com/user/repo.git"
                },
                "git_username": {
                    "description": "Git用户名",
                    "type": "string",
                    "example": "gituser"
                },
                "name": {
                    "description": "项目名称",
                    "type": "string",
                    "example": "我的项目"
                },
                "remark": {
                    "description": "备注",
                    "type": "string",
                    "example": "项目备注信息"
                }
            }
        },
        "models.ProjectUpdateRequest": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "项目编码",
                    "type": "string",
                    "example": "PROJECT001"
                },
                "git_password": {
                    "description": "Git密码",
                    "type": "string",
                    "example": "gitpassword"
                },
                "git_repo": {
                    "description": "Git仓库地址",
                    "type": "string",
                    "example": "https://github.com/user/repo.git"
                },
                "git_username": {
                    "description": "Git用户名",
                    "type": "string",
                    "example": "gituser"
                },
                "name": {
                    "description": "项目名称",
                    "type": "string",
                    "example": "我的项目"
                },
                "remark": {
                    "description": "备注",
                    "type": "string",
                    "example": "项目备注信息"
                }
            }
        },
        "models.Response": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "状态码：200成功，其他失败",
                    "type": "integer",
                    "example": 200
                },
                "data": {
                    "description": "数据：具体返回数据"
                },
                "message": {
                    "description": "消息：成功或失败原因",
                    "type": "string",
                    "example": "操作成功"
                }
            }
        },
        "models.SSHCommandRequest": {
            "type": "object",
            "required": [
                "command",
                "host_id"
            ],
            "properties": {
                "command": {
                    "description": "要执行的命令",
                    "type": "string",
                    "example": "echo 'hello word'"
                },
                "host_id": {
                    "description": "主机ID",
                    "type": "integer",
                    "example": 1
                },
                "timeout": {
                    "description": "超时时间（秒），默认30秒",
                    "type": "integer",
                    "example": 30
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8083",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "DevOps主机管理API",
	Description:      "DevOps自动化部署平台 - 主机管理API文档",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
