/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { GeneratedRoute } from '@elegant-router/types';

export const generatedRoutes: GeneratedRoute[] = [
  {
    name: '403',
    path: '/403',
    component: 'layout.blank$view.403',
    meta: {
      title: '403',
      i18nKey: 'route.403',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '404',
    path: '/404',
    component: 'layout.blank$view.404',
    meta: {
      title: '404',
      i18nKey: 'route.404',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '500',
    path: '/500',
    component: 'layout.blank$view.500',
    meta: {
      title: '500',
      i18nKey: 'route.500',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'home',
    path: '/home',
    component: 'layout.base$view.home',
    meta: {
      title: 'home',
      i18nKey: 'route.home',
      icon: 'mdi:monitor-dashboard',
      order: 1
    }
  },
  {
    name: 'devops',
    path: '/devops',
    component: 'layout.base',
    meta: {
      title: 'DevOps平台',
      i18nKey: 'route.devops',
      icon: 'mdi:rocket-launch',
      order: 2
    },
    children: [
      {
        name: 'devops_dashboard',
        path: '/devops/dashboard',
        component: 'view.devops_dashboard',
        meta: {
          title: '仪表盘',
          i18nKey: 'route.devops_dashboard',
          icon: 'mdi:view-dashboard',
          order: 1
        }
      },
      {
        name: 'devops_host',
        path: '/devops/host',
        component: 'view.devops_host',
        meta: {
          title: '主机管理',
          i18nKey: 'route.devops_host',
          icon: 'mdi:server',
          order: 2
        }
      },
      {
        name: 'devops_application',
        path: '/devops/application',
        component: 'view.devops_application',
        meta: {
          title: '应用管理',
          i18nKey: 'route.devops_application',
          icon: 'mdi:application',
          order: 3
        }
      },
      {
        name: 'devops_build',
        path: '/devops/build',
        component: 'view.devops_build',
        meta: {
          title: '构建管理',
          i18nKey: 'route.devops_build',
          icon: 'mdi:hammer-wrench',
          order: 4
        }
      }
    ]
  },
  {
    name: 'iframe-page',
    path: '/iframe-page/:url',
    component: 'layout.base$view.iframe-page',
    props: true,
    meta: {
      title: 'iframe-page',
      i18nKey: 'route.iframe-page',
      constant: true,
      hideInMenu: true,
      keepAlive: true
    }
  },
  {
    name: 'login',
    path: '/login/:module(pwd-login|code-login|register|reset-pwd|bind-wechat)?',
    component: 'layout.blank$view.login',
    props: true,
    meta: {
      title: 'login',
      i18nKey: 'route.login',
      constant: true,
      hideInMenu: true
    }
  }
];
